---
- name: Add jenkins repository
  yum_repository:
    name: jenkins
    description: Jenkins-stable
    baseurl: http://pkg.jenkins.io/redhat-stable
    gpgcheck: yes
- name: Add jenkins key to rpm db
  rpm_key:
    state: present
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
- name: ensure "jenkins" present
  yum:
    name: jenkins
    state: present
  notify:
    - started jenkins
