---
- name: Add nginx repository
  yum_repository:
    name: nginx-repo
    description: nginx repo
    baseurl: http://nginx.org/packages/centos/7/$basearch
    gpgcheck: no
- name: ensure "nginx" present
  yum:
    name: nginx
    state: present
  notify:
    - start nginx
