---
  
- maven_artifact:
    group_id: "{{ mvn_group_id }}"
    artifact_id: "{{ mvn_artifact_id }}"
    repository_url: "{{ mvn_repo_url }}"
    extension: war
    username: "{{ mvn_repo_user }}"
    password: "{{ mvn_repo_pass }}"
    dest: "{{ tc_webapp_dir }}/ROOT.war"

- name: user
  shell: whoami
  register: whoami
- debug: var=whoami.stdout_lines  

- name: test
  shell: echo $JAVA_HOME
  register: java
- debug: var=java.stdout_lines
 
- name: Stop Tomcat
  shell: /apps/tools/tomcat/bin/shutdown.sh

- name: rm old ver.
  shell: rm -f "{{ tc_webapp_dir }}/ROOT"

- pause:
    seconds: 5

- name: Start Tomcat
  shell: /apps/tools/tomcat/bin/startup.sh
