---
- name: permissive SElinux
  selinux:
    policy: targeted
    state: permissive

- name: ensure "nginx" configured as loadbalancer
  template:
    src: templates/nginx-lb.j2
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx
