---
- name: install the artifactory rpm from a remote repo
  yum:
    name: https://bintray.com/jfrog/artifactory-rpms/download_file?file_path=jfrog-artifactory-oss-5.8.4.rpm
    state: present
- name: ensure artifactory started and enabled
  service:
    name: artifactory
    state: started
    enabled: yes
